// This file was generated by xcresource
// Do Not Edit Directly!

struct ImageKey: ExpressibleByStringLiteral, Hashable {
    var rawValue: String
    
    init(_ rawValue: String) {
        self.rawValue = rawValue
    }
    
    init(stringLiteral value: String) {
        self.rawValue = value
    }
}

// MARK: - Assets.xcassets

extension ImageKey {
    // MARK: Places
    static let places_authArrow: ImageKey = "Places/authArrow"
    static let places_authClose: ImageKey = "Places/authClose"
    
    // MARK: Places/Dot
    static let places_dot_largeOpaque: ImageKey = "Places/Dot/largeOpaque"
    static let places_dot_medium: ImageKey = "Places/Dot/medium"
    static let places_dot_mediumOpaque: ImageKey = "Places/Dot/mediumOpaque"
    
    // MARK: Places/Dot/Outline
    static let places_dot_outlineLarge: ImageKey = "Places/Dot/outlineLarge"
    static let places_dot_outlineMedium: ImageKey = "Places/Dot/outlineMedium"
    
    // MARK: Places/Dot
    static let places_dot_small: ImageKey = "Places/Dot/small"
    
    // MARK: Places
    static let places_filterSaved: ImageKey = "Places/filterSaved"
    static let places_filterTop: ImageKey = "Places/filterTop"
    static let places_list: ImageKey = "Places/list"
    static let places_locationArrow: ImageKey = "Places/locationArrow"
    static let places_map: ImageKey = "Places/map"
    static let places_more: ImageKey = "Places/more"
    static let places_searchEmptyStateOverlay: ImageKey = "Places/searchEmptyStateOverlay"
    static let places_share: ImageKey = "Places/share"
    static let places_showMore: ImageKey = "Places/showMore"
    static let places_suggestionLocation: ImageKey = "Places/suggestionLocation"
    static let places_suggestionText: ImageKey = "Places/suggestionText"
    static let places_userLocation: ImageKey = "Places/userLocation"
    
    // MARK: Settings
    static let settings: ImageKey = "settings"
    static let settingsAnalytics: ImageKey = "settingsAnalytics"
    static let settingsAppearance: ImageKey = "settingsAppearance"
    static let settingsClearCache: ImageKey = "settingsClearCache"
    static let settingsCrash: ImageKey = "settingsCrash"
    static let settingsDev: ImageKey = "settingsDev"
    static let settingsEraseSavedArticles: ImageKey = "settingsEraseSavedArticles"
    static let settingsExplore: ImageKey = "settingsExplore"
    static let settingsFAQ: ImageKey = "settingsFAQ"
    static let settingsFeedback: ImageKey = "settingsFeedback"
    static let settingsHelpAndFeedback: ImageKey = "settingsHelpAndFeedback"
    static let settingsImageDimming: ImageKey = "settingsImageDimming"
    static let settingsLanguage: ImageKey = "settingsLanguage"
    static let settingsNotifications: ImageKey = "settingsNotifications"
    static let settingsPrivacy: ImageKey = "settingsPrivacy"
    static let settingsProject: ImageKey = "settingsProject"
    static let settingsRate: ImageKey = "settingsRate"
    static let settingsSavedArticles: ImageKey = "settingsSavedArticles"
    static let settingsSearch: ImageKey = "settingsSearch"
    static let settingsSupport: ImageKey = "settingsSupport"
    static let settingsTablesExpand: ImageKey = "settingsTablesExpand"
    static let settingsTalkPage: ImageKey = "settingsTalkPage"
    static let settingsTerms: ImageKey = "settingsTerms"
    static let settingsUser: ImageKey = "settingsUser"
    static let settingsZero: ImageKey = "settingsZero"
    
    // MARK: TextFormatting/Layout
    static let textFormattingDecreaseIndent: ImageKey = "textFormattingDecreaseIndent"
    static let textFormattingIncreaseIndent: ImageKey = "textFormattingIncreaseIndent"
    static let textFormattingOrderedList: ImageKey = "textFormattingOrderedList"
    static let textFormattingUnorderedList: ImageKey = "textFormattingUnorderedList"
    
    // MARK: TextFormatting/Style
    static let textFormattingBold: ImageKey = "textFormattingBold"
    static let textFormattingItalics: ImageKey = "textFormattingItalics"
    static let textFormattingStrikethrough: ImageKey = "textFormattingStrikethrough"
    static let textFormattingUnderline: ImageKey = "textFormattingUnderline"
    
    // MARK: TextFormatting
    static let textFormatting: ImageKey = "textFormatting"
    static let textFormattingAdd: ImageKey = "textFormattingAdd"
    static let textFormattingAddCitation: ImageKey = "textFormattingAddCitation"
    static let textFormattingClearFormatting: ImageKey = "textFormattingClearFormatting"
    static let textFormattingCurlyBrackets: ImageKey = "textFormattingCurlyBrackets"
    static let textFormattingFindInPage: ImageKey = "textFormattingFindInPage"
    static let textFormattingLink: ImageKey = "textFormattingLink"
    static let textFormattingStyle: ImageKey = "textFormattingStyle"
}
