// This file was generated by xcresource.
// Do Not Edit Directly!

import Foundation

public struct ColorKey: Hashable, Sendable {
    public let name: String
    public let bundle: Bundle
    
    public init(name: String, bundle: Bundle) {
        self.name = name
        self.bundle = bundle
    }
}

// MARK: - Assets.xcassets

extension ColorKey {
    public static let cobalt: ColorKey = .init(
        name: "cobalt",
        bundle: Bundle.module)
    
    public static let coral: ColorKey = .init(
        name: "coral",
        bundle: Bundle.module)
    
    public static let darkBrown: ColorKey = .init(
        name: "darkBrown",
        bundle: Bundle.module)
    
    public static let lightRose: ColorKey = .init(
        name: "lightRose",
        bundle: Bundle.module)
    
    public static let marigold: ColorKey = .init(
        name: "marigold",
        bundle: Bundle.module)
    
    public static let milkChocolate: ColorKey = .init(
        name: "milkChocolate",
        bundle: Bundle.module)
    
    public enum Warm {
        public static let warmBlue: ColorKey = .init(
            name: "Warm/warmBlue",
            bundle: Bundle.module)
        
        public static let warmGray: ColorKey = .init(
            name: "Warm/warmGray",
            bundle: Bundle.module)
    }
    
    public static let wisteria: ColorKey = .init(
        name: "wisteria",
        bundle: Bundle.module)
}
