// This file was generated by xcresource.
// Do Not Edit Directly!

import Foundation

public struct FileResource: Hashable, Sendable {
    public let relativePath: String
    public let bundle: Bundle
    
    public init(relativePath: String, bundle: Bundle) {
        self.relativePath = relativePath
        self.bundle = bundle
    }
    
    public var url: URL {
        return URL(filePath: relativePath, relativeTo: bundle.resourceURL).standardizedFileURL
    }
    
    public var path: String {
        return url.path(percentEncoded: false)
    }
}

extension FileResource {
    public enum OpenSans {
        public static let openSansBold: FileResource = .init(
            relativePath: "Fonts/OpenSans/OpenSans-Bold.ttf",
            bundle: Bundle.module)
        
        public static let openSansBoldItalic: FileResource = .init(
            relativePath: "Fonts/OpenSans/OpenSans-BoldItalic.ttf",
            bundle: Bundle.module)
        
        public static let openSansExtraBold: FileResource = .init(
            relativePath: "Fonts/OpenSans/OpenSans-ExtraBold.ttf",
            bundle: Bundle.module)
        
        public static let openSansExtraBoldItalic: FileResource = .init(
            relativePath: "Fonts/OpenSans/OpenSans-ExtraBoldItalic.ttf",
            bundle: Bundle.module)
        
        public static let openSansItalic: FileResource = .init(
            relativePath: "Fonts/OpenSans/OpenSans-Italic.ttf",
            bundle: Bundle.module)
        
        public static let openSansLight: FileResource = .init(
            relativePath: "Fonts/OpenSans/OpenSans-Light.ttf",
            bundle: Bundle.module)
        
        public static let openSansLightItalic: FileResource = .init(
            relativePath: "Fonts/OpenSans/OpenSans-LightItalic.ttf",
            bundle: Bundle.module)
        
        public static let openSansMedium: FileResource = .init(
            relativePath: "Fonts/OpenSans/OpenSans-Medium.ttf",
            bundle: Bundle.module)
        
        public static let openSansMediumItalic: FileResource = .init(
            relativePath: "Fonts/OpenSans/OpenSans-MediumItalic.ttf",
            bundle: Bundle.module)
        
        public static let openSansRegular: FileResource = .init(
            relativePath: "Fonts/OpenSans/OpenSans-Regular.ttf",
            bundle: Bundle.module)
        
        public static let openSansSemiBold: FileResource = .init(
            relativePath: "Fonts/OpenSans/OpenSans-SemiBold.ttf",
            bundle: Bundle.module)
        
        public static let openSansSemiBoldItalic: FileResource = .init(
            relativePath: "Fonts/OpenSans/OpenSans-SemiBoldItalic.ttf",
            bundle: Bundle.module)
    }
    
    public static let cambria: FileResource = .init(
        relativePath: "Fonts/Cambria.ttc",
        bundle: Bundle.module)
}
