// This file was generated by xcresource.
// Do Not Edit Directly!

import Foundation

public struct ImageKey: Hashable, Sendable {
    public let name: String
    public let bundle: Bundle
    
    public init(name: String, bundle: Bundle) {
        self.name = name
        self.bundle = bundle
    }
}

// MARK: - Assets.xcassets

extension ImageKey {
    public static let dogWithApple: ImageKey = .init(
        name: "dogWithApple",
        bundle: Bundle.module)
    
    public enum Places {
        public static let authArrow: ImageKey = .init(
            name: "Places/authArrow",
            bundle: Bundle.module)
        
        public enum Dot {
            public static let medium: ImageKey = .init(
                name: "Places/Dot/medium",
                bundle: Bundle.module)
            
            public static let small: ImageKey = .init(
                name: "Places/Dot/small",
                bundle: Bundle.module)
        }
        
        public static let map: ImageKey = .init(
            name: "Places/map",
            bundle: Bundle.module)
        
        public static let suggestionLocation: ImageKey = .init(
            name: "Places/suggestionLocation",
            bundle: Bundle.module)
    }
    
    public enum Style {
        public static let textFormattingBold: ImageKey = .init(
            name: "Style/textFormattingBold",
            bundle: Bundle.module)
        
        public static let textFormattingItalic: ImageKey = .init(
            name: "Style/textFormattingItalic",
            bundle: Bundle.module)
        
        public static let textFormattingStrikethrough: ImageKey = .init(
            name: "Style/textFormattingStrikethrough",
            bundle: Bundle.module)
        
        public static let textFormattingUnderline: ImageKey = .init(
            name: "Style/textFormattingUnderline",
            bundle: Bundle.module)
    }
    
    public static let textFormatting: ImageKey = .init(
        name: "textFormatting",
        bundle: Bundle.module)
    
    public static let textFormattingCurlyBrackets: ImageKey = .init(
        name: "textFormattingCurlyBrackets",
        bundle: Bundle.module)
    
    public static let textFormattingFindInPage: ImageKey = .init(
        name: "textFormattingFindInPage",
        bundle: Bundle.module)
    
    public static let textFormattingLink: ImageKey = .init(
        name: "textFormattingLink",
        bundle: Bundle.module)
}
