// This file was generated by xcresource
// Do Not Edit Directly!

struct StringForm {
    let key: String
    let arguments: [CVarArg]
    
    init(key: String, arguments: [CVarArg]) {
        self.key = key
        self.arguments = arguments
    }
}

// MARK: - StringForm generated from StringKey

extension StringForm {
    /// 동영상 첨부는 최대 %ld분, %@까지 가능합니다.\n다른 파일을 선택해주세요.
    static func alert_attachTooLargeVideo(_ param1: Int, _ param2: String) -> StringForm {
        return StringForm(
            key: StringKey.alert_attachTooLargeVideo.rawValue,
            arguments: [param1, param2])
    }
    
    /// %{changeCount}ld changes made
    static func changeDescription(changeCount: Int) -> StringForm {
        return StringForm(key: StringKey.changeDescription.rawValue, arguments: [changeCount])
    }
    
    /// My dog ate %#@appleCount@ today!
    static func dogEatingApples(appleCount: Int) -> StringForm {
        return StringForm(key: StringKey.dogEatingApples.rawValue, arguments: [appleCount])
    }
}
