// This is a generated file, do not edit!
// Generated by generate-keylist

@testable import ResourceKeyApp

extension StringKey {
    static let allGeneratedKeys: [StringKey] = [
        // MARK: StringKey.swift
        .common_cancel,
        .common_confirm,
        .common_done,
        .editMenu_aspectRatio,
        .editMenu_aspectRatioGuide,
        .editMenu_bgm,
        .editMenu_bgm_placeholder,
        .editMenu_copyright,
        .editMenu_copyright_placeholder,
        .editMenu_filter,
        .editMenu_filter_original,
        .errorPopup_cancelToEditAsset,
        .errorPopup_failToAttach,
        .errorPopup_failToLoadAsset,
        .errorPopup_failToLoadBGMList,
        .errorPopup_failToEncoding,
        .errorPopup_overMaximumSize,
    ]
}
