import Foundation
import ArgumentParser
import AssetKeyGen
import Util

let headerComment = """
// This is a generated file, do not edit!
// Generated by \(ProcessInfo.processInfo.processName)
"""

extension AssetType: ExpressibleByArgument {
    public init?(argument: String) {
        switch argument {
        case "image":   self = .imageSet
        case "color":   self = .colorSet
        case "symbol":  self = .symbolSet
        default:        return nil
        }
    }
    
    public var defaultValueDescription: String {
        return "image"
    }
    
    public static var allValueStrings: [String] {
        return ["image", "color", "symbol"]
    }
}

struct GenerateAssetKeys: ParsableCommand {
    static let configuration: CommandConfiguration = .init(
        abstract: "Asset Catalog 가지고 키 파일 생성.",
        discussion: """
            Xcode Asset Catalog(.xcassets)에서 리소스 이름을 추출해서 키 파일을 생성한다.
            추출한 키 파일은 앱 개발 시 리소스 로딩에 사용할 수 있다.
            """)
    
    @Option(name: .customLong("input-xcassets"))
    var inputXCAssets: [String]
    
    @Option(help: ArgumentHelp(valueName: "image, color, or symbol"))
    var assetType: AssetType = .imageSet
    
    @Option var keyTypeName: String
    
    @Option(help: "<key-list-file>에 '@testable import <module-name>' 추가")
    var moduleName: String?
    
    @Flag var excludeTypeDeclation: Bool = false
    
    @Option var keyDeclFile: String
    
    @Option var keyListFile: String?
    
    mutating func run() throws {
        let codes = try generateCodes()
        
        try writeKeyDeclFile(from: codes)
        
        try writeKeyListFileIfNeeded(from: codes)
    }
    
    private func generateCodes() throws -> AssetKeyGenerator.Result {
        let request = AssetKeyGenerator.Request(
            catalogURLs: inputXCAssets.map({ URL(fileURLWithExpandingTildeInPath: $0) }),
            assetType: assetType,
            keyTypeName: keyTypeName)
        
        return try AssetKeyGenerator().generate(for: request)
    }
    
    private func writeKeyDeclFile(from codes: AssetKeyGenerator.Result) throws {
        let tempFileURL = FileManager.default.makeTemporaryFileURL()
        var stream = try TextFileOutputStream(forWritingTo: tempFileURL)
        
        print(headerComment, terminator: "\n\n", to: &stream)
        
        if !excludeTypeDeclation {
            print(codes.typeDeclaration, terminator: "\n\n", to: &stream)
        }
        
        print(codes.keyDeclarations, to: &stream)
        
        try stream.close()
        try FileManager.default.compareAndMoveFile(from: tempFileURL, to: keyDeclFile)
    }
    
    private func writeKeyListFileIfNeeded(from codes: AssetKeyGenerator.Result) throws {
        guard let keyListFile = keyListFile else { return }
        
        let tempFileURL = FileManager.default.makeTemporaryFileURL()
        var stream = try TextFileOutputStream(forWritingTo: tempFileURL)
        
        print(headerComment, terminator: "\n\n", to: &stream)
        
        if let moduleName = moduleName {
            print("@testable import \(moduleName)", terminator: "\n\n", to: &stream)
        }
        
        print(codes.keyList, to: &stream)
        
        try stream.close()
        try FileManager.default.compareAndMoveFile(from: tempFileURL, to: keyListFile)
    }
}

GenerateAssetKeys.main()
