// This file was generated by xcresource
// Do Not Edit Directly!

import Foundation

public struct FontResource: Hashable {
    public var fontName: String
    public var familyName: String
    public var style: String
    public var relativePath: String
    public var bundle: Bundle
    
    public init(
        fontName: String,
        familyName: String,
        style: String,
        relativePath: String,
        bundle: Bundle
    ) {
        self.fontName = fontName
        self.familyName = familyName
        self.style = style
        self.relativePath = relativePath
        self.bundle = bundle
    }
    
    public var url: URL {
        return URL(filePath: relativePath, relativeTo: bundle.resourceURL)
    }
}

public extension FontResource {
    static let all: [FontResource] = [
        // Cambria
        .cambria_regular,
        
        // Cambria Math
        .cambriaMath_regular,
        
        // Open Sans
        .openSans_bold,
        .openSans_boldItalic,
        .openSans_extraBold,
        .openSans_extraBoldItalic,
        .openSans_italic,
        .openSans_light,
        .openSans_lightItalic,
        .openSans_medium,
        .openSans_mediumItalic,
        .openSans_regular,
        .openSans_semiBold,
        .openSans_semiBoldItalic,
    ]
}

public extension FontResource {
    // MARK: Cambria
    
    static let cambria_regular: FontResource = .init(
        fontName: "Cambria",
        familyName: "Cambria",
        style: "Regular",
        relativePath: "Fonts/Cambria.ttc",
        bundle: Bundle.module)
    
    // MARK: Cambria Math
    
    static let cambriaMath_regular: FontResource = .init(
        fontName: "CambriaMath",
        familyName: "Cambria Math",
        style: "Regular",
        relativePath: "Fonts/Cambria.ttc",
        bundle: Bundle.module)
    
    // MARK: Open Sans
    
    static let openSans_bold: FontResource = .init(
        fontName: "OpenSans-Bold",
        familyName: "Open Sans",
        style: "Bold",
        relativePath: "Fonts/OpenSans/OpenSans-Bold.ttf",
        bundle: Bundle.module)
    
    static let openSans_boldItalic: FontResource = .init(
        fontName: "OpenSans-BoldItalic",
        familyName: "Open Sans",
        style: "Bold Italic",
        relativePath: "Fonts/OpenSans/OpenSans-BoldItalic.ttf",
        bundle: Bundle.module)
    
    static let openSans_extraBold: FontResource = .init(
        fontName: "OpenSans-ExtraBold",
        familyName: "Open Sans",
        style: "ExtraBold",
        relativePath: "Fonts/OpenSans/OpenSans-ExtraBold.ttf",
        bundle: Bundle.module)
    
    static let openSans_extraBoldItalic: FontResource = .init(
        fontName: "OpenSans-ExtraBoldItalic",
        familyName: "Open Sans",
        style: "ExtraBold Italic",
        relativePath: "Fonts/OpenSans/OpenSans-ExtraBoldItalic.ttf",
        bundle: Bundle.module)
    
    static let openSans_italic: FontResource = .init(
        fontName: "OpenSans-Italic",
        familyName: "Open Sans",
        style: "Italic",
        relativePath: "Fonts/OpenSans/OpenSans-Italic.ttf",
        bundle: Bundle.module)
    
    static let openSans_light: FontResource = .init(
        fontName: "OpenSans-Light",
        familyName: "Open Sans",
        style: "Light",
        relativePath: "Fonts/OpenSans/OpenSans-Light.ttf",
        bundle: Bundle.module)
    
    static let openSans_lightItalic: FontResource = .init(
        fontName: "OpenSans-LightItalic",
        familyName: "Open Sans",
        style: "Light Italic",
        relativePath: "Fonts/OpenSans/OpenSans-LightItalic.ttf",
        bundle: Bundle.module)
    
    static let openSans_medium: FontResource = .init(
        fontName: "OpenSans-Medium",
        familyName: "Open Sans",
        style: "Medium",
        relativePath: "Fonts/OpenSans/OpenSans-Medium.ttf",
        bundle: Bundle.module)
    
    static let openSans_mediumItalic: FontResource = .init(
        fontName: "OpenSans-MediumItalic",
        familyName: "Open Sans",
        style: "Medium Italic",
        relativePath: "Fonts/OpenSans/OpenSans-MediumItalic.ttf",
        bundle: Bundle.module)
    
    static let openSans_regular: FontResource = .init(
        fontName: "OpenSans-Regular",
        familyName: "Open Sans",
        style: "Regular",
        relativePath: "Fonts/OpenSans/OpenSans-Regular.ttf",
        bundle: Bundle.module)
    
    static let openSans_semiBold: FontResource = .init(
        fontName: "OpenSans-SemiBold",
        familyName: "Open Sans",
        style: "SemiBold",
        relativePath: "Fonts/OpenSans/OpenSans-SemiBold.ttf",
        bundle: Bundle.module)
    
    static let openSans_semiBoldItalic: FontResource = .init(
        fontName: "OpenSans-SemiBoldItalic",
        familyName: "Open Sans",
        style: "SemiBold Italic",
        relativePath: "Fonts/OpenSans/OpenSans-SemiBoldItalic.ttf",
        bundle: Bundle.module)
}
