// This is a generated file, do not edit!
// Generated by generate-asset-keys

struct ImageKey: ExpressibleByStringLiteral, Hashable {
    var rawValue: String
    
    init(_ rawValue: String) {
        self.rawValue = rawValue
    }
    
    init(stringLiteral value: String) {
        self.rawValue = value
    }
}

// MARK: - Assets.xcassets

extension ImageKey {
    static let appIcon: ImageKey = "AppIcon"
    
    // MARK: Common/BGMNavigationBar
    static let icoMusic: ImageKey = "icoMusic"
    static let icoMusicPressed: ImageKey = "icoMusicPressed"
    
    // MARK: Common
    static let btnSelect: ImageKey = "btnSelect"
    
    // MARK: Common/ClipListView
    static let icoAdd: ImageKey = "icoAdd"
    static let icoAddPressed: ImageKey = "icoAddPressed"
    
    // MARK: Common/ErrorPopupView
    static let icon_check_normal: ImageKey = "icon_check_normal"
    static let icon_check_pressed: ImageKey = "icon_check_pressed"
    
    // MARK: Common
    static let icoClose: ImageKey = "icoClose"
    static let icoClosePressed: ImageKey = "icoClosePressed"
    static let icoConfirm: ImageKey = "icoConfirm"
    static let icoConfirmPressed: ImageKey = "icoConfirmPressed"
    
    // MARK: Common/NavigationBar
    static let icoFoldDown: ImageKey = "icoFoldDown"
    static let icoFoldDownPressed: ImageKey = "icoFoldDownPressed"
    static let icoFoldUp: ImageKey = "icoFoldUp"
    static let icoFoldUpPressed: ImageKey = "icoFoldUpPressed"
    
    // MARK: Common/PlayButton
    static let icoPause: ImageKey = "icoPause"
    static let icoPlay: ImageKey = "icoPlay"
    
    // MARK: Component
    static let btnHandle: ImageKey = "btnHandle"
    
    // MARK: Component/Common
    static let component_icoDelete: ImageKey = "component.icoDelete"
    static let component_icoFold: ImageKey = "component.icoFold"
    static let component_icoKeyboard: ImageKey = "component.icoKeyboard"
    static let component_icoKeyboardPressed: ImageKey = "component.icoKeyboardPressed"
    static let component_icoPreview: ImageKey = "component.icoPreview"
    static let component_icoSearch: ImageKey = "component.icoSearch"
    
    // MARK: Component/ComponentIcons
    static let component_blog: ImageKey = "component.blog"
    static let component_book: ImageKey = "component.book"
    static let component_date: ImageKey = "component.date"
    static let component_link: ImageKey = "component.link"
    static let component_movie: ImageKey = "component.movie"
    static let component_news: ImageKey = "component.news"
    static let component_place: ImageKey = "component.place"
    
    // MARK: Component/PlaceSearch/LocationAgreementWebView
    static let se_nt_ico_on_1: ImageKey = "se_nt_ico_on_1"
    static let se_nt_ico_on_2: ImageKey = "se_nt_ico_on_2"
    
    // MARK: Component/PlaceSearch
    static let placeSearch_icoLocation: ImageKey = "PlaceSearch.icoLocation"
    static let placeSearch_icoPinSearch: ImageKey = "PlaceSearch.icoPinSearch"
    
    // MARK: Scenes/Editing/BGMEditor
    static let btnAddNormal: ImageKey = "btnAddNormal"
    static let btnAddPressed: ImageKey = "btnAddPressed"
    static let btnPauseSmallNormal: ImageKey = "btnPauseSmallNormal"
    static let btnPlaySmallNormal: ImageKey = "btnPlaySmallNormal"
    
    // MARK: Scenes/Editing/Component
    static let component_icoFoldPressed: ImageKey = "component.icoFoldPressed"
    static let logoVlog34: ImageKey = "logoVlog34"
    
    // MARK: Scenes/Editing/DetailEdit/Color
    static let detailEdit_color_icoAdjustment: ImageKey = "DetailEdit/Color/icoAdjustment"
    static let detailEdit_color_icoAdjustmentOn: ImageKey = "DetailEdit/Color/icoAdjustmentOn"
    static let detailEdit_color_icoBrightness: ImageKey = "DetailEdit/Color/icoBrightness"
    static let detailEdit_color_icoContrast: ImageKey = "DetailEdit/Color/icoContrast"
    static let detailEdit_color_icoFilter: ImageKey = "DetailEdit/Color/icoFilter"
    static let detailEdit_color_icoFilterOn: ImageKey = "DetailEdit/Color/icoFilterOn"
    
    // MARK: Scenes/Editing/DetailEdit/Copyright
    static let detailEdit_checkOnTop: ImageKey = "DetailEdit/checkOnTop"
    static let detailEdit_copyrightCheckOff: ImageKey = "DetailEdit/copyrightCheckOff"
    static let detailEdit_imgVideoCopy: ImageKey = "DetailEdit/imgVideoCopy"
    
    // MARK: Scenes/Editing/DetailEdit/Volume
    static let detailEdit_icoMusicSmall: ImageKey = "DetailEdit/icoMusicSmall"
    static let detailEdit_icoMusicSmallMute: ImageKey = "DetailEdit/icoMusicSmallMute"
    
    // MARK: Scenes/Editing/EditMenuIcons
    static let icoColorEdit: ImageKey = "icoColorEdit"
    static let icoColorEditPressed: ImageKey = "icoColorEditPressed"
    static let icoCrop: ImageKey = "icoCrop"
    static let icoCropPressed: ImageKey = "icoCropPressed"
    static let icoDraw: ImageKey = "icoDraw"
    static let icoDrawPressed: ImageKey = "icoDrawPressed"
    static let icoSound: ImageKey = "icoSound"
    static let icoSoundPressed: ImageKey = "icoSoundPressed"
    
    // MARK: Scenes/Editing/PopupNavigation
    static let btnStyle1: ImageKey = "btnStyle1"
    static let btnStyle2: ImageKey = "btnStyle2"
    
    // MARK: Scenes/Editing
    static let previewGradationTop: ImageKey = "previewGradationTop"
    
    // MARK: Scenes/PreviewPlayer
    static let previewPlayerPause: ImageKey = "previewPlayerPause"
    static let previewPlayerPlay: ImageKey = "previewPlayerPlay"
    
    // MARK: Scenes/Publish
    static let icoClear12: ImageKey = "icoClear12"
    static let icoDownloader: ImageKey = "icoDownloader"
    static let icoDownloaderPressed: ImageKey = "icoDownloaderPressed"
    static let icoMerge: ImageKey = "icoMerge"
    static let icoTip: ImageKey = "icoTip"
    
    // MARK: Scenes/Snapshot
    static let iconCheck: ImageKey = "iconCheck"
    static let iconCheckOff: ImageKey = "iconCheckOff"
    static let numBg1: ImageKey = "numBg1"
    static let numBg2: ImageKey = "numBg2"
    
    // MARK: Scenes/Style
    static let iconLeftArrow: ImageKey = "iconLeftArrow"
    static let iconLeftArrowDisable: ImageKey = "iconLeftArrowDisable"
    static let iconRightArrow: ImageKey = "iconRightArrow"
    static let iconRightArrowDisable: ImageKey = "iconRightArrowDisable"
    
    // MARK: TextEditor
    static let icoAlignCenter: ImageKey = "icoAlignCenter"
    static let icoAlignCenterAct: ImageKey = "icoAlignCenterAct"
    static let icoAlignLeft: ImageKey = "icoAlignLeft"
    static let icoAlignLeftAct: ImageKey = "icoAlignLeftAct"
    static let icoAlignRight: ImageKey = "icoAlignRight"
    static let icoAlignRightAct: ImageKey = "icoAlignRightAct"
}
