// This file was generated by xcresource
// Do Not Edit Directly!

public struct ColorKey: ExpressibleByStringLiteral, Hashable {
    public var rawValue: String
    
    public init(_ rawValue: String) {
        self.rawValue = rawValue
    }
    
    public init(stringLiteral value: String) {
        self.rawValue = value
    }
}

// MARK: - Assets.xcassets

public extension ColorKey {
    // MARK: Color
    static let cobalt: ColorKey = "cobalt"
    static let coral: ColorKey = "coral"
    static let darkBrown: ColorKey = "darkBrown"
    static let lightRose: ColorKey = "lightRose"
    static let marigold: ColorKey = "marigold"
    static let milkChocolate: ColorKey = "milkChocolate"
    static let warmBlue: ColorKey = "warmBlue"
    static let warmGray: ColorKey = "warmGray"
    static let wisteria: ColorKey = "wisteria"
}
