// This file was generated by xcresource
// Do Not Edit Directly!

public struct StringForm {
    public var key: String
    public var arguments: [CVarArg]
    
    public init(key: String, arguments: [CVarArg]) {
        self.key = key
        self.arguments = arguments
    }
}

// MARK: - StringForm generated from StringKey

public extension StringForm {
    /// Undo %{command}@
    static func editMenu_undo(command: String) -> StringForm {
        return StringForm(key: StringKey.editMenu_undo.rawValue, arguments: [command])
    }
    
    /// Redo %{command}@
    static func editMenu_redo(command: String) -> StringForm {
        return StringForm(key: StringKey.editMenu_redo.rawValue, arguments: [command])
    }
    
    /// %{_ fileCount}ld files
    static func fileList_fileCount(_ fileCount: Int) -> StringForm {
        return StringForm(key: StringKey.fileList_fileCount.rawValue, arguments: [fileCount])
    }
    
    /// "%{fileName}@" will be deleted.\n
    /// This action cannot be undone.
    static func alert_delete_file(fileName: String) -> StringForm {
        return StringForm(key: StringKey.alert_delete_file.rawValue, arguments: [fileName])
    }
    
    /// %{dogName}@ ate %#@appleCount@ today!
    static func dog_eating_apples(dogName: String, appleCount: Int) -> StringForm {
        return StringForm(
            key: StringKey.dog_eating_apples.rawValue,
            arguments: [dogName, appleCount])
    }
}
