// This file was generated by xcresource
// Do Not Edit Directly!

public struct ImageKey: ExpressibleByStringLiteral, Hashable, Sendable {
    public let rawValue: String
    
    public init(_ rawValue: String) {
        self.rawValue = rawValue
    }
    
    public init(stringLiteral value: String) {
        self.rawValue = value
    }
}

// MARK: - Assets.xcassets

public extension ImageKey {
    // MARK: Photo
    static let dogWithApple: ImageKey = "dogWithApple"
    
    // MARK: Places
    static let places_authArrow: ImageKey = "Places/authArrow"
    
    // MARK: Places/Dot
    static let places_dot_medium: ImageKey = "Places/Dot/medium"
    static let places_dot_small: ImageKey = "Places/Dot/small"
    
    // MARK: Places
    static let places_map: ImageKey = "Places/map"
    static let places_suggestionLocation: ImageKey = "Places/suggestionLocation"
    
    // MARK: TextFormatting/Style
    static let textFormattingBold: ImageKey = "textFormattingBold"
    static let textFormattingItalic: ImageKey = "textFormattingItalic"
    static let textFormattingStrikethrough: ImageKey = "textFormattingStrikethrough"
    static let textFormattingUnderline: ImageKey = "textFormattingUnderline"
    
    // MARK: TextFormatting
    static let textFormatting: ImageKey = "textFormatting"
    static let textFormattingCurlyBrackets: ImageKey = "textFormattingCurlyBrackets"
    static let textFormattingFindInPage: ImageKey = "textFormattingFindInPage"
    static let textFormattingLink: ImageKey = "textFormattingLink"
}
