// This is a generated file, do not edit!
// Generated by generate-asset-keys

@testable import ResourceKeyApp

extension ColorKey {
    static let allGeneratedKeys: [ColorKey] = [
        // MARK: Assets.xcassets
        .accentColor,
        .battleshipGrey8,
        .battleshipGrey12,
        .cobalt,
        .coral,
        .coralPink,
        .coralTwo,
        .darkBrown,
        .lightRose,
        .marigold,
        .milkChocolate,
        .offWhite,
        .orangered,
        .orangeyRed,
        .orangeyRedTwo,
        .paleGrey18,
        .paleGrey30,
        .paleGrey60,
        .warmBlue,
        .warmGrey,
        .weirdGreen,
        .white5,
        .wisteria,
    ]
}
