// This is a generated file, do not edit!
// Generated by generate-keylist

@testable import ResourceKeyApp

extension StringKey {
    static let allGeneratedKeys: [StringKey] = [
        // MARK: StringKey.swift
        .editing_menu_addBGM,
    ]
}
